services:
  app:
    build: 
      # context: .
      # dockerfile: Dockerfile.hfsubset
      image: ghcr.io/taddyb33/hfsubset-legacy:0.0.2
    ports:
      - "8008:8000"
    volumes:
      - type: bind
        source: ./data/rfc_geopackage_data
        target: /app/data
    command: sh -c ". /app/.venv/bin/activate && uvicorn src.hfsubset.app.main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: curl --fail -I http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
